---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
  namespace: couchbase

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
  namespace: couchbase
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaserolebindings
  - couchbasebackups
  - couchbasebackuprestores
  - couchbaseautoscalers
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
  namespace: couchbase
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: couchbase-operator-admission
subjects:
- kind: ServiceAccount
  name: couchbase-operator-admission
  namespace: couchbase

---
apiVersion: v1
data:
  tls-cert-file: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpakNDQW5LZ0F3SUJBZ0lSQUpUc3gzWGwyelpQRVBHbi9kM055bDB3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZlkyOTFZMmhpWVhObExXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJpQkRRVEFlRncweQpNVEF4TURZeE9EQTRNamxhRncwek1UQXhNRFF4T0RBNE1qbGFNQ2N4SlRBakJnTlZCQU1USEdOdmRXTm9ZbUZ6ClpTMXZjR1Z5WVhSdmNpMWhaRzFwYzNOcGIyNHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQ29RY0xkKzFzL0NJb2FoOGJRVHFmVEgyTGJqMTErYnV3VW1TSGJsL1ZNd1VJRFJvQnE1eEE5Z1FRTAo5d055VXBoRVFWek5KMDZ0UWZ1SzBWVFcwTWNQa2dVRGZPZjAvWFM3MWkvMG0vTGlxRGc3MmkzYWFQM3lVWGF5CkhhdG1WOXNXZGF4THovTWlzclNZMzN4QnB5TzB6Uit3VHFJbDB2b1lGRVBXOWdmQkFRMnAvcTM3WXFKQVArYSsKbjg0eUU5a0RqbDJBNlB4SmxMa0xaYVJJdkZOdmdYeFRFQXorVStVWFBPZXNRUnZucEtRYmZFaEhtSXR3a2Y0SAowYUxhbVRVSE51S1BDRUFBREMwLzBubGRUcDh3MGdKeGZ2M1E4OWRpcnliSjBtbVBLLzU0VGhJTEFPZFlFWFk1CkpqdTBYYzZJU0N1WGRyOVgyN042Z2FPcWhCakZBZ01CQUFHamdhMHdnYW93RGdZRFZSMFBBUUgvQkFRREFnV2cKTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkZEaQp6RDJTYnU3V3lGOFQ2WjR2dGhsT1N5SkpNQjhHQTFVZEl3UVlNQmFBRkVlUnNPazY3d0Zlam5HUm5GM0p0SzloCmNVbThNRFVHQTFVZEVRUXVNQ3lDS21OdmRXTm9ZbUZ6WlMxdmNHVnlZWFJ2Y2kxaFpHMXBjM05wYjI0dVkyOTEKWTJoaVlYTmxMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQW1LcHpHeVE3Q2tnVVNGWnU4UmNuY0dUUQowSXVEcFNWdDFNMy9UdVdNTHpWTm42aXRiNE1GVFoydVBRVWx0bGI4UDdudm9GOHFNTzkvVVhnY3JHVHZRQ1p0CnJHZlNwRGtzTjRGVlZ4OWNjamNndTNXZ1R3bzlyODVVUlA1aVV0Z05sazJuRUZENGhmUkI0Q0VNMVJlUXptazYKU0VHUG9haGZlS0FpbW16WmdnWUZHQmE2OUNSQXJHTWFpVWlkQW0xSk9sdWxQT3JjOVBRMVhCd254TFdDczI2UQpmVHphQ1BEdHhjSzVJbFhqeGpuWXY5Yk9JUFJyQzE2QUlHSGlVQ1NIMkFuQjBXNW9EVW1ZL09pSHBaN3JtTzJxCkdZeGJ5bzdsVWlUL2ZtbllWdVhlQTV6RjdtRmZKNVFXYzhjZzFkNVhOUnBxTUxsT3MwMVNxNlM0S0VhemNnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls-private-key-file: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBcUVIQzNmdGJQd2lLR29mRzBFNm4weDlpMjQ5ZGZtN3NGSmtoMjVmMVRNRkNBMGFBCmF1Y1FQWUVFQy9jRGNsS1lSRUZjelNkT3JVSDdpdEZVMXRESEQ1SUZBM3puOVAxMHU5WXY5SnZ5NHFnNE85b3QKMm1qOThsRjJzaDJyWmxmYkZuV3NTOC96SXJLMG1OOThRYWNqdE0wZnNFNmlKZEw2R0JSRDF2WUh3UUVOcWY2dAorMktpUUQvbXZwL09NaFBaQTQ1ZGdPajhTWlM1QzJXa1NMeFRiNEY4VXhBTS9sUGxGenpuckVFYjU2U2tHM3hJClI1aUxjSkgrQjlHaTJwazFCemJpandoQUFBd3RQOUo1WFU2Zk1OSUNjWDc5MFBQWFlxOG15ZEpwanl2K2VFNFMKQ3dEbldCRjJPU1k3dEYzT2lFZ3JsM2EvVjl1emVvR2pxb1FZeFFJREFRQUJBb0lCQUZaZVUxSXhXWmhVb05lWApoTldlMm9VRUluSEQrT0VTdlRxaGxJQ3RVeXlRTTN1TThCUndBYVVnbWR3dWN1VjNRbFFmSFN6dUZYUFlYKy9WCkhuQ2FnT1FjTjFpZ0FFMkE0VEFlZFVWaDI5Ni9MUWFFSzI5bTM1eElkdDVkWG9OTmE5ZnVsWC9oQWRSNDJUMXoKMHN1OHFSYUJDTmd1dFFzbmJsdDM0NDd2Z2ZGdTdMNllDMlBlUnQ5QWtkemEvWHo1amRFZVJobytSSUVvZlZyOQprNjhKa0VJb2FRWUwzbFgzUGE5dERKbCttM2hQM25pOU8xcDJyK3N3NlVpdlU0WTlTRjhoWTJENEM5UmtIeXBKCi8rSHZWaVZYVFVoV0krdDBqdGs0OHB2RmhSdGExSHM1Wm9lNTBoNzBucEFyd05hVmFIRXB3bkphblB6ZndvWEMKbUxkNWh3RUNnWUVBMkIrSk8yaU1QRlh0bWVlZVJQV1RBNXR6NmdiQ2Q3Y2docjAzVmI1cGtseTJSU1J0ZURMMApna1JJNXZMRE5PTUtYYjM5NTAzQ2dEeURySHBES1hwVGhEbWpwdVY0QkhRZTFkWWZPRzNQREw3RUxLSHVrMFpWCnlWOHBIMmpOdnlpOEFVd1FycXY5dTd2M0YrYnp1YTJONmM3K0V0MjV3bGlEYWZJeWtMSTQrOEVDZ1lFQXgwMUoKRnlLbU9RR083eEd6Z3JVYU9hVWFQSUFUWGJLOEMwR01tQjgra2lOMk1xcUYyQWNtaDA3Sjc1VlFQSXR4N2Zjdwp0bjhxbTY3bTBBdWxTVjZQdm9NK3EyVE9WRzFiN0JyQldtM0NBVEZlSHYwd1pPMjFSUkp5cGVacWwzbkNWZDh0Ck9DT2RrdGFBbGlBRUlGaGJQa04xVnBXZFBzK0JGSVRXZ2s3S3JnVUNnWUI2RUwyNm54N3RpUDdNdVVQcjRPT3EKMnVjS0c4MUVQbHNSbnRjZEI1R3JCOUF1bHhkNUZ4YUFhTDdnS2ViVS9STEN4V2NkZUE3TnpOLzF6NHdWWmpDNwpjcTZhdWVvaVljOTBxUjR6Q2RveWNhQnRNUHlGaytrcDlpUk15QzNFdE9ZU3VYcUduVCtQQStmWVNTb0pDaHdvCkhTL2xTZlA3NzNBeHE0aWhydmQrUVFLQmdDSVlxc1IyZlJHTG5yUnZ4dEk1d1g3VExDWGxrMnFZUld0M2oySUgKRm1GU0I4cXJPYkszcG5QSG11eU9FdWdJd3pqKzdTcUxudko3ZmFsaUZLajBzSXJiVVVGcFFaTllFajNXWmZYZQppUzVERCtNbFZiNHVuTEJ3YzRUR1lyMy9hcXZlUHBJNEphRVZhWEpGais4b3JwTjhYdnF0SmZXMDhsUmNWWVo5CmpGY3hBb0dBWk1nVTUrbFljcXBmUFJOZzRGOUVEYld2RHdudi9VL2x2TUM3QVZwWVNvcDY5dHNldWt1TGczNHYKT2hLamtzVUs1VjlqbVd4WHVvTVIraUs1eTlJeS8ycHdCQUt0UjZsTEtLbHJCaDRPZGpoSFErS3Z1KytVdlNGSwpId1ZyZjdxWGhyY3l4Z2dZUDJNR3ZLaFE3TFJIcHZlRmg5djBPSWxtZmRyUDc2NnVwWnc9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
  namespace: couchbase

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
  namespace: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator-admission
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchbase-operator-admission
    spec:
      containers:
      - args:
        - --logtostderr
        - --stderrthreshold
        - "0"
        - --tls-cert-file
        - /var/run/secrets/couchbase.com/couchbase-operator-admission/tls-cert-file
        - --tls-private-key-file
        - /var/run/secrets/couchbase.com/couchbase-operator-admission/tls-private-key-file
        command:
        - couchbase-operator-admission
        image: couchbase/admission-controller:2.1.0
        name: couchbase-operator-admission
        ports:
        - containerPort: 8443
          name: https
        readinessProbe:
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
        resources: {}
        volumeMounts:
        - mountPath: /var/run/secrets/couchbase.com/couchbase-operator-admission
          name: couchbase-operator-admission
          readOnly: true
      serviceAccountName: couchbase-operator-admission
      volumes:
      - name: couchbase-operator-admission
        secret:
          secretName: couchbase-operator-admission
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
  namespace: couchbase
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: couchbase-operator-admission
status:
  loadBalancer: {}

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lRRTVYKys5RFdVZzFHM3hIY29yOUlrVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5amIzVmphR0poYzJVdGIzQmxjbUYwYjNJdFlXUnRhWE56YVc5dUlFTkJNQjRYRFRJeApNREV3TmpFNE1EZ3lPVm9YRFRNeE1ERXdOREU0TURneU9Wb3dLakVvTUNZR0ExVUVBeE1mWTI5MVkyaGlZWE5sCkxXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJpQkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTncxK09zY0ZNQ3BTUHkzRUNpMFk5OUdTWW16UUhweVpPRWpESmE4L1pmRVUrZnpucURqd2xscgpVS3Z2YTJISzQ4K3ZKS1NXUmJXZW9ySkl1MnFBZ0VCcXVNLzN5K1dKREtUaXlSV2VDMHpocmtINXgybTRvb2ZmCmxZbEFlSXdxREd6alJRUWk5VDhEOUxGMGJkSElXWmhPNk40SWtjbFpuam50cytTMlEyeldSamZzaEVuNGRLTGwKRUpmejBjaU9kSFpNTVZsSHBHVlpXeTkrQ1ZLMWlIaHFYVWc1eHpKSkdDaFZHazA0aTB0SW5ZWU1kRm41c05wNwpEYTBJdVhGUUlTWFA4V0V3ODIrODJ5L1BXVlRlak9BTXhGMUcwY2xWMU91TFVKWC9LRmo5Q3VoT0NJUFZqUzNRCmY5R25mT3htbG9ja3JnTXdOVnVYVVpvZW5rZE04V2tDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUcKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkVlUnNPazY3d0Zlam5HUm5GM0p0SzloY1VtOApNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFkZDlHNXVrRW40ZHhvRUlrTlBIRWRGK1RRdTlUd2JrZDZiemJqCmd5V1JEcVE5dXFRc3I4YzFEalptZUxxMmpHdEQzc1lYZk5WMk1pOVY5aHhkUURGRUNNU3p5MHhKcHlYMFd1NkMKZXh2NzhBbFI1dzAyUHlZc2M3V0pvOW0vK3VoRmR5U0ZyLytIMmFiUjJhR0hqQkEzNlEwTmlHRGNYS05ORWFnYwpuNjBCbFVuZUVBMmNuRDBIelI4TTZRTDd3R3Q1d2c4cEk5bGV3SlQxUFJvTW1CTzVESmpzQlJGUlYwUFlkRGpNCjRPMjQ3V3JNZ1djbmg2Y2ZuUmR1NVgwcWhhdFFtazRla1V5SUp3c0FpaDRKWHhjeHk1MlhUUG1Ma0dGL1AxVTcKNldpM3F2YVFaQTZRYzJHVEJJamdTa1k5YUl1aTZJOTFZT1NQZHdRa3VCNUlVb3g1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: couchbase-operator-admission
      namespace: couchbase
      path: /couchbaseclusters/mutate
  failurePolicy: Fail
  name: couchbase-operator-admission.couchbase.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQWdpZ0F3SUJBZ0lRRTVYKys5RFdVZzFHM3hIY29yOUlrVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5amIzVmphR0poYzJVdGIzQmxjbUYwYjNJdFlXUnRhWE56YVc5dUlFTkJNQjRYRFRJeApNREV3TmpFNE1EZ3lPVm9YRFRNeE1ERXdOREU0TURneU9Wb3dLakVvTUNZR0ExVUVBeE1mWTI5MVkyaGlZWE5sCkxXOXdaWEpoZEc5eUxXRmtiV2x6YzJsdmJpQkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTncxK09zY0ZNQ3BTUHkzRUNpMFk5OUdTWW16UUhweVpPRWpESmE4L1pmRVUrZnpucURqd2xscgpVS3Z2YTJISzQ4K3ZKS1NXUmJXZW9ySkl1MnFBZ0VCcXVNLzN5K1dKREtUaXlSV2VDMHpocmtINXgybTRvb2ZmCmxZbEFlSXdxREd6alJRUWk5VDhEOUxGMGJkSElXWmhPNk40SWtjbFpuam50cytTMlEyeldSamZzaEVuNGRLTGwKRUpmejBjaU9kSFpNTVZsSHBHVlpXeTkrQ1ZLMWlIaHFYVWc1eHpKSkdDaFZHazA0aTB0SW5ZWU1kRm41c05wNwpEYTBJdVhGUUlTWFA4V0V3ODIrODJ5L1BXVlRlak9BTXhGMUcwY2xWMU91TFVKWC9LRmo5Q3VoT0NJUFZqUzNRCmY5R25mT3htbG9ja3JnTXdOVnVYVVpvZW5rZE04V2tDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUcKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkVlUnNPazY3d0Zlam5HUm5GM0p0SzloY1VtOApNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFkZDlHNXVrRW40ZHhvRUlrTlBIRWRGK1RRdTlUd2JrZDZiemJqCmd5V1JEcVE5dXFRc3I4YzFEalptZUxxMmpHdEQzc1lYZk5WMk1pOVY5aHhkUURGRUNNU3p5MHhKcHlYMFd1NkMKZXh2NzhBbFI1dzAyUHlZc2M3V0pvOW0vK3VoRmR5U0ZyLytIMmFiUjJhR0hqQkEzNlEwTmlHRGNYS05ORWFnYwpuNjBCbFVuZUVBMmNuRDBIelI4TTZRTDd3R3Q1d2c4cEk5bGV3SlQxUFJvTW1CTzVESmpzQlJGUlYwUFlkRGpNCjRPMjQ3V3JNZ1djbmg2Y2ZuUmR1NVgwcWhhdFFtazRla1V5SUp3c0FpaDRKWHhjeHk1MlhUUG1Ma0dGL1AxVTcKNldpM3F2YVFaQTZRYzJHVEJJamdTa1k5YUl1aTZJOTFZT1NQZHdRa3VCNUlVb3g1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: couchbase-operator-admission
      namespace: couchbase
      path: /couchbaseclusters/validate
  failurePolicy: Fail
  name: couchbase-operator-admission.couchbase.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    - v2
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters
    - couchbasebuckets
    - couchbaseephemeralbuckets
    - couchbasememcachedbuckets
    - couchbasereplications
    - couchbaseusers
    - couchbasegroups
    - couchbaserolebindings
    - couchbasebackups
    - couchbasebackuprestores
    - couchbaseautoscalers
  sideEffects: None

