apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: couchbase-auth
  namespace: couchbase
spec:
  encryptedData:
    password: AgBPvDO+069F7JQRPPpP869H66wkn0b3fITeBxryny5PTRumTqOBLpbKFnmhJ+ZP2ePK9JFs4UxKarPpYFsR8omEvee7YwPpr05OWY4EfB8m9wPs5RToKmP2FnbZ0fYEkP2Rr+A+6FllNMw3AZL8WQNzeKjveD35xTgkrxS1ERY2lDYj5lENIReGte7aIOpNyPVnJIgqXwrWmNiARUytUT7pU7WwowZdAH6i6m4Q22I23gWSJ9NDNK4kbNTjG/QaSvzoD+oX30edJ5nLawMVoq6bi46tXUGepVRxpf0DeYVRyOqJhj+n3+RJ8EuoTSZw4hS8mA1GUiw47/oO4UzBAYjzDqtWm/73lrWY3CMiexoCY+BDIfRuX6zET8YrlwOoJXATrYJv+IJkAolIpAhYrFo793YP7Fao31ufoLmccMoXVfx2LQ40PgeqY6dhKjuDi7xL8JfQEWgyD2qiC6c3CjTwiECeFSI0Em5NI1dYJm1p9sgqnw5ujZIYzsHQAZmMEqt865ba8VHq94GlprSdqog9R19XH79fZYcB3O+CVwJ93ikdN0qQGdx6Oz4ABl7y7mH7XXnoSaiK9uhgKDAUq92uniJDWQmgSrWUWA/pkyOk3UaF6H8bQPt6KSU3a/flrPTIOizqfZJzh5SBXJmh3vHbSzGkh1CLDI+GStpEIx2XByZNiMiZDa3P8DXRC3VVh3P37sg0dvNelMqaaJql
    username: AgBXMz/wSrLrcLtReRC1ID51xfGOfeeaKyOu2R5CTNu+f2PXj8nWGhuPiZfKl3e8AHmQmXUhLut1TAyIvYQmBTCbNcC11XgkmTdeJepjOz184Bvxb06i4vsAKD+tIPPz+OdzJMvYYn3/lJ5RBqwkuK/Wnr7AsmL9iMIkO3iGK4OvWumODn4koXyQrcJiEwTeo5Fq0V++42/dUPh5u5qt7BXCzbyz+hD431Zgla/vWNj1yAC6Mkk2bzQBZDwS9c9sc1SVw4m20LOUHoAWxr9gkmyp8cSMjBuZ+WaKYtICYv8G/0tX9evq5vJQ4Ipvu3/Px98mtVIIt3kjQ9qxi4kEGUEIo3UKfkyVKaV0J73GLZHdPUlBMhj2SPhCdLhUAZXC2WQ+xa+ThuRkhVnOrw0tZtBgMRFquoBJraktepDpAtYc2AAhCBAP3MfSeo54R5frJaE6Os6XL23G2dEBNiZ0IGv51k7JWZP9tQ5xepQc4lmmHao0uVT27Cizz+DVORaq6dmJ8sEG5WzWcLb3idCLGs2hopyLEz4ZZu5SpzUKAICmctF5Hbo9Y6DdF7/cSaLXIVM3lGlt4lBiiW88ghzSFMK+8X2/DG+RIhUVoK+vp+oGeeQQx/I1FvdqFSgFvnf0TA6OdBezJdzmjGAk+3RhbeK80iwQ23gquY49urdTpJpDxyMTar5a1lxIlRcSXtL1mpY0tXQ63Q==
  template:
    metadata:
      creationTimestamp: null
      name: couchbase-auth
      namespace: couchbase
    type: Opaque

